/**
 * One slide in the presentation.
 */
export interface Slide {
  title: string;
  body: string[];
  notes?: string;
}

/**
 * Design metadata for a single slide, generated by the Design Agent.
 */
export interface SlideDesign {
  layout: "hero" | "bullets" | "split" | "quote" | "stats" | "big-number" | "minimal";
  accentColor: string;
  gradientFrom: string;
  gradientTo: string;
  gradientAngle: number;
  icon: string;
  darkText: boolean;
  highlightLines: number[];
  tagline?: string;
}

/**
 * Blackboard: array of 5 slides (index 0..4). null = not yet written.
 */
export type Blackboard = (Slide | null)[];

/**
 * Design blackboard: array of 5 designs (index 0..4). null = not yet generated.
 */
export type DesignBoard = (SlideDesign | null)[];

export const SLIDE_COUNT = 5;
